version: '3.1'

volumes:
  postgresql_data:

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=hotel_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=vdJ#cZ8s